version: '3.8'
services:
  nextjs-hello-world:
    image: nextjs-hello-world
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"