name: Push Docker Image to ACR on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acr0dev.azurecr.io
          identity: 'managed'  # Use 'managed' to indicate that you're using a managed identity    

      - name: Push Docker image to ACR
        run: |
          docker buildx create --use
          docker buildx inspect

          docker push acr0dev.azurecr.io/next-hello-world:${CURRENT_DATE} .
